repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--fix, commerce_platform, tests]
      - id: ruff-format
        args: [commerce_platform, tests]
