product:
  name: Pink_DS
  display_name: Pink Dualsense
  links:
    amazon: https://www.amazon.in/dp/B09SM63G1L?smid=AT95IG9ONZD7S
    shopatsc: https://shopatsc.com/collections/all/products/dualsense-controller-pink-rus
  hidden: false
  notification_roles:
    '889437492477046785': 893734593621000232
  notification_channels:
    '889437492477046785': 892795445112369183
  affiliate_links:
    amazon: https://www.amazon.in/dp/B09SM63G1L/?tag=consolesindiaid-21
  add_to_cart_links:
    amazon: https://www.amazon.in/gp/aws/cart/add.html?AssociateTag=consolesindiaid-21&ASIN.1=B09SM63G1L&Quantity.1=1
  wishlist: https://www.amazon.in/hz/wishlist/ls/K5HVAMY70DJ5/
  colour: 196608
  emoji: <:Black_Dualsense:864361710532952064>
  key: PINK_DS
