product:
  name: PS5_DE
  display_name: PS5 Digital
  links:
    amazon: https://www.amazon.in/dp/B09V58Q6DY
    flipkart: https://www.flipkart.com/sony-playstation-5-cfi-1008b01r-825-gb-astro-s-playroom/p/itm8bf74f8d0b890?
    shopatsc: https://shopatsc.com/products/playstation5-digital-edition
    games_the_shop: https://www.gamestheshop.com/PlayStation-5-Digital-Edition/5112
    e2zstore: https://e2zstore.com/product/playstation-5-digital-edition-ps5/
    reliance: https://www.reliancedigital.in/sony-playstation-5-console/p/491936181
  hidden: false
  notification_roles:
    '797570077364977696': 857134006243688458
    '889437492477046785': 893734151428132894
  notification_channels:
    '889437492477046785': 892795445112369183
    '797570077364977696': 850096085770567700
  affiliate_links:
    amazon: https://www.amazon.in/Sony-CFI-1008B01R-PlayStation-Digital-Edition/dp/B09V58Q6DY/?tag=consolesindiaid-21
  add_to_cart_links:
    amazon: https://www.amazon.in/gp/aws/cart/add.html?AssociateTag=consolesindiaid-21&ASIN.1=B09V58Q6DY&Quantity.1=1
    shopatsc: https://shopatsc.com/cart/34426793427083:1
  wishlist: https://www.amazon.in/hz/wishlist/ls/K5HVAMY70DJ5/
  twitter_hashtags: '#RestockPS5India #PS5Digital'
  thumbnail_link: https://i.imgur.com/pmgar66.jpg?1
  colour: 36607
  emoji: <:PS5_DE:893792926705020960>
  key: PS5_DE
