product:
  name: PS5_DE_HFW_BUNDLE
  display_name: PS5 DE & HFW bundle
  links:
    amazon: https://www.amazon.in/dp/B0B9GDVHQQ/
    shopatsc: https://shopatsc.com/collections/playstation-5/products/playstation-5-digital-edition-with-horizon-forbidden-west-voucher-inside-box
    flipkart: https://www.flipkart.com/sony-cfi-1108b01r-825-gb-ssd-horizon-forbidden-west-for-ps5-voucher-inside-box/p/itm3783a181f39d4
  hidden: false
  notification_roles:
    '797570077364977696': 849606173522788352
    '889437492477046785': 893734056720740352
  notification_channels:
    '889437492477046785': 892795445112369183
    '797570077364977696': 850096085770567700
  affiliate_links:
    amazon: https://www.amazon.in/dp/B0B9GDVHQQ/?tag=consolesindiaid-21
  add_to_cart_links:
    amazon: https://www.amazon.in/gp/aws/cart/add.html?AssociateTag=consolesindiaid-21&ASIN.1=B09YD71MZT&Quantity.1=1
    shopatsc: https://shopatsc.com/cart/40739661742219:1
  wishlist: https://www.amazon.in/hz/wishlist/ls/K5HVAMY70DJ5/
  twitter_hashtags: '#RestockPS5India #PS5'
  thumbnail_link: https://i.imgur.com/pmgar66.jpg?1
  colour: 2162943
  emoji: <:PS5:893792926050684929>
  key: PS5_DE_HFW_BUNDLE
