product:
  name: PS_WISHLIST
  display_name: Playstation Wishlist
  links:
    amazon: https://www.amazon.in/hz/wishlist/ls/K5HVAMY70DJ5/
  hidden: true
  subproducts:
  - PS5
  - PS5_DE
  - PS5_Camera_Bundle
  - PS5_DE_Remote_Bundle
  - PS5_DE_Pulse_Bundle
  - PS5_DE_Charging_Station_Bundle
  colour: 0
  emoji: <:PS5:893792926050684929>📜
  key: PS_WISHLIST
