product:
  name: RED_DS
  display_name: Red Dualsense
  links:
    amazon: https://www.amazon.in/DualSense-Wireless-Controller-Red-PlayStation/dp/B098439Y2G?smid=AT95IG9ONZD7S
    shopatsc: https://shopatsc.com/products/dualsense-wireless-controller-red
  hidden: false
  notification_roles:
    '889437492477046785': 893734512255701035
  notification_channels:
    '889437492477046785': 892795445112369183
  affiliate_links:
    amazon: https://www.amazon.in/DualSense-Wireless-Controller-Red-PlayStation/dp/B098439Y2G/?tag=consolesindiaid-21
  add_to_cart_links:
    amazon: https://www.amazon.in/gp/aws/cart/add.html?AssociateTag=consolesindiaid-21&ASIN.1=B098439Y2G&Quantity.1=1
  wishlist: https://www.amazon.in/hz/wishlist/ls/K5HVAMY70DJ5/
  colour: 16711680
  emoji: <:Red_Dualsense:864361711183593472>
  key: RED_DS
