product:
  name: ROG_ALLY_Z1_EXTREME
  display_name: ROG Ally Z1 Extreme
  links:
    flipkart: https://www.flipkart.com/asus-rog-ally-ryzen-z1-octa-core-extreme-16-gb-512-gb-ssd-windows-11-home-rc71l-nh001w-handheld-gaming-pc/p/itm194f7d5e14ede?pid=COMGQKQ7GGNFR8N4
  hidden: false
  twitter_hashtags: '#RestockPS5India #PS5 #PS5India'
  colour: 0
  key: ROG_ALLY_Z1_EXTREME
