product:
  name: XBOX_WISHLIST
  display_name: Xbox Wishlist
  links:
    amazon: https://www.amazon.in/hz/wishlist/ls/18WU5P3MXFWL0/
  hidden: true
  subproducts:
  - XSX
  - XSX_HALO_EDITION
  - XSX_Gears_Tactics_Bundle
  - XSX_White_Controller_Bundle
  - XSX_Black_Controller_Bundle
  - XSX_Blue_Controller_Bundle
  colour: 0
  emoji: <:XSX:893792926574972929>📜
  key: XBOX_WISHLIST
