product:
  name: XSS
  display_name: XSS
  links:
    amazon: https://www.amazon.in/Xbox-Series-S/dp/B08J89D6BW/?smid=AT95IG9ONZD7S
    flipkart: https://www.flipkart.com/microsoft-xbox-series-s-512-gb/p/itm13c51f9047da8
    e2zstore: https://prepaidgamercard.com/product/xbox-series-s/
    reliance: https://www.reliancedigital.in/xbox-series-s-console-with-wireless-controller-512-gb/p/491934659
  hidden: false
  notification_roles:
    '889437492477046785': 893734365476057119
  notification_channels:
    '889437492477046785': 893754612547481630
  affiliate_links:
    amazon: https://www.amazon.in/Xbox-Series-S/dp/B08J89D6BW/?tag=consolesindiaid-21
  add_to_cart_links:
    amazon: https://www.amazon.in/gp/aws/cart/add.html?AssociateTag=?tag=consolesindiaid-21&ASIN.1=B08J89D6BW&Quantity.1=1
  wishlist: https://www.amazon.in/hz/wishlist/ls/18WU5P3MXFWL0/
  twitter_hashtags: '#XboxSeriesS #XSS'
  thumbnail_link: https://i.imgur.com/OpInEum.jpg
  colour: 6148957
  emoji: <:XSS:893792927090884628>
  key: XSS
