product:
  name: XSX_HALO_EDITION_CONTROLLER
  display_name: XSX Halo Edition Elite controller
  links:
    amazon: https://www.amazon.in/dp/B09LMY7K1L/
    flipkart: https://www.flipkart.com/microsoft-xbox-elite-wireless-controller-series-2-halo-infinite-limited-bluetooth-gamepad/p/itm28256af2eb91a
    e2zstore: https://prepaidgamercard.com/product/xbox-elite-wireless-controller-series-2-halo-infinite-limited-edition/
  hidden: false
  notification_channels:
    '889437492477046785': 893754612547481630
  affiliate_links:
    amazon: https://www.amazon.in/Xbox-Series-X/dp/B09LMY7K1L/?tag=consolesindiaid-21
  add_to_cart_links:
    amazon: https://www.amazon.in/gp/aws/cart/add.html?AssociateTag=consolesindiaid-21&ASIN.1=B09LMY7K1L&Quantity.1=1
  wishlist: https://www.amazon.in/hz/wishlist/ls/18WU5P3MXFWL0/
  twitter_hashtags: '#RestockXSXIndia #XboxSeriesX #XSX #Halo #'
  thumbnail_link: https://i.imgur.com/WpKbZXR.jpg
  colour: 4098054
  emoji: <:XSX:893792926574972929>
  key: XSX_HALO_EDITION_CONTROLLER
