product:
  name: XSX_WHITE_CONTROLLER_BUNDLE
  display_name: XSX & Robot White Controller bundle
  links:
    amazon: https://www.amazon.in/dp/B08NRLS39X/?smid=AT95IG9ONZD7S
  hidden: false
  notification_roles:
    '889437492477046785': 893734236392144926
  notification_channels:
    '889437492477046785': 893754612547481630
  affiliate_links:
    amazon: https://www.amazon.in/Xbox-Series-X/dp/B08NRLS39X/?tag=consolesindiaid-21
  add_to_cart_links:
    amazon: https://www.amazon.in/gp/aws/cart/add.html?AssociateTag=consolesindiaid-21&ASIN.1=B08NRLS39X&Quantity.1=1
  wishlist: https://www.amazon.in/hz/wishlist/ls/18WU5P3MXFWL0/
  twitter_hashtags: '#RestockXSXIndia #XboxSeriesX #XSX'
  thumbnail_link: https://i.imgur.com/WpKbZXR.jpg
  colour: 4098054
  emoji: <:XSX:893792926574972929>
  key: XSX_WHITE_CONTROLLER_BUNDLE
